language: node_js

node_js:
- "8"

branches:
  only:
    - master

cache:
  directories:
    - $HOME/.npm
    - $HOME/.yarn-cache
    - node_modules

install:
- yarn install

script:
- yarn run publish
